#ifndef DT_BINDINGS_PINCTRL_INGENIC_H
#define DT_BINDINGS_PINCTRL_INGENIC_H

#define PIN_MODE_FUNCTION_0	0
#define PIN_MODE_FUNCTION_1	1
#define PIN_MODE_FUNCTION_2	2
#define PIN_MODE_FUNCTION_3	3

#define PIN_MODE_GPIO		255

#endif /* DT_BINDINGS_PINCTRL_INGENIC_H */
