#
# Jz4740 Platform Support
#
snd-soc-jz4740-i2s-objs := jz4740-i2s.o

obj-$(CONFIG_SND_JZ4740_SOC_I2S) += snd-soc-jz4740-i2s.o

# Jz4740 Machine Support
snd-soc-qi-lb60-objs := qi_lb60.o

# GCW Zero support
snd-soc-gcw0-objs := gcw0.o

obj-$(CONFIG_SND_JZ4740_SOC_QI_LB60) += snd-soc-qi-lb60.o
obj-$(CONFIG_SND_JZ4770_SOC_GCW0) += snd-soc-gcw0.o
